# -*- coding: utf-8 -*-
"""bài 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1az4iS1d4x2f3maef-szXAJzBIxQtDbso
"""

import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
x_with_nan

x

math.isnan(np.nan), np.isnan(math.nan)

y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
y

y_with_nan

z

z_with_nan

math.isnan(y_with_nan[3]), np.isnan(y_with_nan[3])

mean_ = sum(x) / len(x)
mean_

mean_ = statistics.mean(x)
mean_

statistics?

mean_ = statistics.fmean(x)

"""không hỗ trợ fmean"""

mean_ = statistics.mean(x_with_nan)
mean_

mean_ = np.mean(y)
mean_

mean_ = y.mean()
mean_

np.nanmean(y_with_nan)

mean_ = z.mean()
mean_

z_with_nan.mean()

0.2 * 2 + 0.5 * 4 + 0.3 * 8

x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
wmean

y, z, w = np.array(x), pd.Series(x), np.array(w)
wmean = np.average(y, weights=w)
wmean

wmean = np.average(z, weights=w)
wmean

(w * y).sum() / w.sum()

w = np.array([0.1, 0.2, 0.3, 0.0, 0.2, 0.1])
(w * y_with_nan).sum() / w.sum()

np.average(y_with_nan, weights=w)

np.average(z_with_nan, weights=w)

hmean = len(x) / sum(1 / item for item in x)
hmean

w = np.array([0.1, 0.2, 0.3, 0.0, 0.2, 0.1])
 (w * y_with_nan).sum() / w.sum()

np.average(y_with_nan, weights=w)

np.average(z_with_nan, weights=w)

hmean = len(x) / sum(1 / item for item in x)
hmean

hmean = statistics.harmonic_mean(x)
hmean

statistics.harmonic_mean(x_with_nan)

statistics.harmonic_mean([1, 0, 2])

statistics.harmonic_mean([1, 2, 2])

"""không hỗ trợ giá trị âm"""

scipy.stats.hmean(z)

scipy.stats.hmean(y)

gmean = 1
for item in x:
  gmean *= item

gmean **= 1 / len(x)
gmean

gmean = statistics.mean(x)
gmean

scipy.stats.gmean(y)

scipy.stats.gmean(z)

n = len(x)
if n % 2:
  median_ = sorted(x)[round(0.5*(n-1))]
else:
  x_ord, index = sorted(x), round(0.5 * n)
  median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

median_ = statistics.median(x)
median_

median_ = statistics.median(x[:-1])
median_

statistics.median_low(x[:-1])

statistics.median_high(x[:-1])

statistics.median(x_with_nan)

statistics.median_low(x_with_nan)

statistics.median_high(x_with_nan)

median_ = np.median(y)
median_

median_ = np.median(y[:-1])
median_

np.nanmedian(y_with_nan)

np.nanmedian(y_with_nan[:-1])